### ISSUE TITLE
Make it possible to sign up for a rehearsal slot on it's own

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#90] opened 2020-02-20 19:57 UTC
Currrently, you have to fill out your complete tech form in order to sign up for a rehearsal slot.  Can we break things out so people can just sign up for a slot and fill out tech info later?

**Comment by bethlakshmi** [comment] 2020-02-22 22:46
Duplicate of #91 at this point.

**Comment by bethlakshmi** [comment] 2020-03-07 02:59
Fixed by #91

**Closed by bethlakshmi** 2020-03-07 02:59 UTC
Labels: enhancement, high
