### ISSUE TITLE
Big warning when performer leaves Act Name blank

### ISSUE THREAD

**Issue by burlexpo** [bethlakshmi/gbe-divio-djangocms-python2.7#462] opened 2023-05-22 23:39 UTC
When a performer tries to submit an act without a name, throw up a big warning banner that says "You Are Trying To Submit This Act Without A Name" and if they confirm, then I think we want to use the song name and not the performer's.

**Comment by bethlakshmi** [comment] 2023-07-13 01:03
We talked recently.  Notes:
- instead of making an auto-title with name + conference slug...
- start with it blank (and required)
- if they submit and haven't filled it out say - "this act will be saved with the title '<your name> - <song title>' is that OK?  this note would come up whether the act is saved as draft or as submit.  It needs a title either way.
    - if they say "no" - it goes back to the act edit screen, with a blank title, and they can fill in what they want.
    - if they say "yes" - it's saved that way
 - if the act is a duplicate of a previous act - then it's saved as "Performer - Song - number" where number = 2, 3, 4, etc.

I will change the uniqueness rules if needed to make sure it's only requiring uniqueness of name + title + conference - so if they re-propose an act w. an old song, it can reuse the same title

**Comment by bethlakshmi** [comment] 2023-09-17 14:31
OK.  Setting the title to blank and putting in some help text was easy:

<img width="758" alt="Screenshot 2023-09-17 at 10 12 41 AM" src="https://github.com/bethlakshmi/gbe-divio-djangocms-python2.7/assets/4542707/2ed52c27-abba-44e5-8166-3c492024bfb6">

Having some logic problems with the popup.  Both because it's a new pattern for us, and because I am not a javascript/jquery wiz.  Here's my biggest heartache:

1 - if there are multiple missing required fields, a popup about 1 field is misleading.  It will look like we have suggested a fix that fixes everything, and we are only fixing the name of act.
2 - the "Track Title" (ie, song title) is optional - so it isn't a solution in all cases.  Do I even display the popup if there's no title?
3 - if they have multiple acts with the same title in this conference --- do they really want multiple acts with the same title?  No one is going to remember which is which.

**Counter proposal:**

- if the act is submitted with any errors - put an error alert message at the top of the page - we have a lot of instruction text and it hides that the form had errors.  A red box at the top would help.  It will have an editable text response - like "You must fix the errors on your form before you can save a draft of/submit your act" (two different messages depending on which thing they did.  It could also enumerate the errors.  **Do we want that?**

- if one of the errors is an empty act name - I can update the form to put the track title in there - and note it in the error message for that field.

- if the act name is a duplicate for this performer &.conference - I'll note it in the alert at the top, and give a link to the other act, with a note to give this act a different title.

- if we really hate the idea of a red error message instead of a popup, I could see about doing the same error messaging in popup form, but the user would still have to ack the popup, and then go to the form and submit it.

**Comment by bethlakshmi** [comment] 2023-09-20 22:44
pushing to site now.

**Closed by bethlakshmi** 2023-09-20 22:44 UTC
Labels: PR-ready
